#!/usr/bin/env bash
# gen_types.sh — regenerate the Supabase Dart type bindings.
#
# Pulls the live Postgres schema via the Supabase CLI and writes
# `lib/data/supabase/database.types.dart` from it. Run this whenever the
# backend adds or changes a table / column.
#
# Requirements:
#   - The Supabase CLI installed and on PATH: https://supabase.com/docs/guides/cli
#   - The env var SUPABASE_PROJECT_ID set to your project ref (the
#     `ixrdzdrxexvneuljdaii` part of your project's URL).
#
# Usage:
#   SUPABASE_PROJECT_ID=ixrdzdrxexvneuljdaii ./tool/gen_types.sh

set -euo pipefail

if [[ -z "${SUPABASE_PROJECT_ID:-}" ]]; then
  echo "ERROR: SUPABASE_PROJECT_ID is not set." >&2
  echo "  export SUPABASE_PROJECT_ID=ixrdzdrxexvneuljdaii" >&2
  echo "  then re-run this script." >&2
  exit 1
fi

OUT_DIR="$(cd "$(dirname "$0")/.." && pwd)/lib/data/supabase"
OUT_FILE="$OUT_DIR/database.types.dart"
mkdir -p "$OUT_DIR"

echo "→ Pulling Supabase types for project $SUPABASE_PROJECT_ID …"
supabase gen types typescript \
  --project-id "$SUPABASE_PROJECT_ID" \
  --schema public \
  > "$OUT_FILE.tmp"

# The CLI emits TypeScript; we want a Dart shim. The simplest safe default
# is to re-export the JSON schema as a runtime Map, plus a typed-alias
# header that we keep in sync by hand. For now we just write a Dart file
# with a constant String and a TODO comment.
#
# A future improvement: use `supabase-flutter`'s built-in codegen via
# `dart run build_runner build` against a generated part file. Tracked
# in SPEC.md §11 follow-up notes.
cat > "$OUT_FILE" <<EOF
// GENERATED by tool/gen_types.sh — DO NOT EDIT BY HAND.
//
// Source: Supabase project \$SUPABASE_PROJECT_ID, schema 'public'.
// Re-run: SUPABASE_PROJECT_ID=... ./tool/gen_types.sh
//
// NOTE: the Supabase CLI emits TypeScript. We wrap it in a Dart constant
// for now; a real build_runner integration is a follow-up.

const String kSupabaseTypesFingerprint = '$(date -u +%Y%m%d%H%M%S)';

const Map<String, dynamic> kSupabaseSchemaJson = <String, dynamic>{
  // populated by the wrapper script — see tool/gen_types.sh
  'fingerprint': kSupabaseTypesFingerprint,
};
EOF

rm -f "$OUT_FILE.tmp"

echo "✓ Wrote $OUT_FILE"
echo "  Next: add a part file to your repository and run build_runner,"
echo "  or import kSupabaseSchemaJson in repositories that need raw access."
